# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper.rb"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration

require 'mbsy'
require 'rspec'
require 'fakeweb'
require 'factory_girl'
require 'faker'
require 'factories'

FakeWeb.allow_net_connect = false

Mbsy.configure do |c|
  c.api_key = 'test'
  c.user_name = 'test'
end

RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus
end

def fake_domain
  "https://#{Mbsy.site_uri}/"
end